# Generated by Django 3.2.6 on 2021-08-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostmodel',
            old_name='match_date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='hostmodel',
            old_name='match_time',
            new_name='event_time',
        ),
        migrations.RemoveField(
            model_name='guestmodel',
            name='URL',
        ),
        migrations.RemoveField(
            model_name='guestmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='URL',
        ),
    ]
