# Generated by Django 3.2.6 on 2021-08-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0002_auto_20210828_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='image',
            field=models.ImageField(upload_to='C:/Users/owner/sofutomo/media'),
        ),
    ]
