# Generated by Django 3.2.6 on 2021-08-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0005_alter_guestmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmodel',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
