# Generated by Django 3.2.6 on 2021-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0006_alter_guestmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
