# Generated by Django 3.2.6 on 2021-08-31 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0007_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='image',
        ),
    ]
