# Generated by Django 3.2.6 on 2021-08-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0009_goodmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmodel',
            name='location',
        ),
    ]
