# Generated by Django 3.2.6 on 2021-09-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0013_matchmodel_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='matchmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='matchmodel',
            name='gender',
        ),
    ]
