# Generated by Django 3.2.6 on 2021-09-16 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0014_auto_20210914_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_name1',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user_name2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
