# Generated by Django 3.2.6 on 2021-09-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0015_auto_20210916_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_name1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_name2',
        ),
    ]
